# generated by Neptune Namespaces v0.1.0
# file: caffeine_script/index.coffee

(module.exports = require './namespace')
.includeInNamespace(require './caffeine_script')
.addModules
  WrappedCoffeeScript: require './wrapped_coffee_script'