# generated by Neptune Namespaces v0.1.0
# file: caffeine_script/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.CaffeineScript ||
Neptune.addNamespace class CaffeineScript extends Neptune.Base
  ;