# generated by Neptune Namespaces
# file: caffeine_script/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.CaffeineScript ||
Neptune.addNamespace class CaffeineScript extends Neptune.Base
  ;