# generated by Neptune Namespaces v0.1.0
# file: caffeine/compilers/index.coffee

(module.exports = require './namespace')
.addModules
  CoffeeScript: require './coffee_script'
  JavaScript:   require './java_script'