# generated by Neptune Namespaces v0.3.0
# file: caffeine/compilers/namespace.coffee

Caffeine = require '../namespace'
module.exports = Caffeine.Compilers ||
Caffeine.addNamespace 'Compilers', class Compilers extends Neptune.Base
  ;