# generated by Neptune Namespaces v0.1.0
# file: caffeine/compilers/namespace.coffee

Caffeine = require '../namespace'
module.exports = Caffeine.Compilers ||
Caffeine.addNamespace class Compilers extends Neptune.Base
  ;