// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/index.js

(module.exports = require('./namespace'))
.includeInNamespace(require('./CaffeineScript'))
.addModules({
  CaffeineScriptParser:       require('./CaffeineScriptParser'),
  CafParseNodeBaseClass:      require('./CafParseNodeBaseClass'),
  JavaScriptReservedWordList: require('./JavaScriptReservedWordList'),
  JavaScriptReservedWords:    require('./JavaScriptReservedWords'),
  Lib:                        require('./Lib'),
  OperatorHelper:             require('./OperatorHelper'),
  Preprocessors:              require('./Preprocessors'),
  StandardImport:             require('./StandardImport'),
  StnRegistry:                require('./StnRegistry')
});
require('./Rules');
require('./SemanticTree');