# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.PackageNamespace
  @version: require('../../package.json').version
require './Rules/namespace';
require './SemanticTree/namespace'