# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/MultipleToJs/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AssignmentStn: require './AssignmentStn'