# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/MultipleToJs/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.MultipleToJs ||
SemanticTree.addNamespace 'MultipleToJs', class MultipleToJs extends Neptune.Base
  ;
