# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/MultipleToJs/namespace.coffee

module.exports = (require '../namespace').addNamespace('MultipleToJs', class MultipleToJs extends Neptune.PackageNamespace)
