# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/SimpleToJs/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  AccessorStn:           require './AccessorStn'          
  ArrayDestructuringStn: require './ArrayDestructuringStn'
  ArraySpreadElementStn: require './ArraySpreadElementStn'
  ArrayStn:              require './ArrayStn'             