# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/SimpleToJs/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.SimpleToJs ||
SemanticTree.addNamespace 'SimpleToJs', class SimpleToJs extends Neptune.Base
  ;
