# generated by Neptune Namespaces v1.x.x
# file: syntaxHighlighting/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.SyntaxHighlighting ||
Neptune.addNamespace 'SyntaxHighlighting', class SyntaxHighlighting extends Neptune.Base
  ;