// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/Rules/index.js

(module.exports = require('./namespace'))

.addModules({
  Accessors:               require('./Accessors'),
  ArrayLiterals:           require('./ArrayLiterals'),
  Assignment:              require('./Assignment'),
  Blocks:                  require('./Blocks'),
  Classes:                 require('./Classes'),
  Comments:                require('./Comments'),
  Comprehensions:          require('./Comprehensions'),
  ControlStructures:       require('./ControlStructures'),
  DestructuringAssignment: require('./DestructuringAssignment'),
  Expressions:             require('./Expressions'),
  Extract:                 require('./Extract'),
  Functions:               require('./Functions'),
  KeywordLiterals:         require('./KeywordLiterals'),
  Literals:                require('./Literals'),
  NumberLiterals:          require('./NumberLiterals'),
  ObjectLiterals:          require('./ObjectLiterals'),
  Operators:               require('./Operators'),
  RegExp:                  require('./RegExp'),
  Require:                 require('./Require'),
  Root:                    require('./Root'),
  Statements:              require('./Statements'),
  StringLiterals:          require('./StringLiterals'),
  TagMacros:               require('./TagMacros'),
  Tokens:                  require('./Tokens'),
  ValueLists:              require('./ValueLists'),
  Values:                  require('./Values')
});