// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/Rules/namespace.js

module.exports = require('../namespace').addNamespace(
  'Rules',
  class Rules extends Neptune.PackageNamespace {}
);
