# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/Rules/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.Rules ||
CaffeineScript.addNamespace 'Rules', class Rules extends Neptune.Base
  ;
