# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/TransformOnlyStns/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  CaptureStn:             require './CaptureStn'            
  ComprehensionStn:       require './ComprehensionStn'      
  ExtractStn:             require './ExtractStn'            
  ExtractToIdentifierStn: require './ExtractToIdentifierStn'