// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/TransformOnlyStns/index.js

(module.exports = require('./namespace'))

.addModules({
  CaptureStn:             require('./CaptureStn'),
  ComprehensionStn:       require('./ComprehensionStn'),
  ExtractStn:             require('./ExtractStn'),
  ExtractToIdentifierStn: require('./ExtractToIdentifierStn'),
  StandardImport:         require('./StandardImport')
});