// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/TransformOnlyStns/namespace.js

module.exports = require('../namespace').addNamespace(
  'TransformOnlyStns',
  class TransformOnlyStns extends Neptune.PackageNamespace {}
);
