# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/TransformOnlyStns/namespace.coffee

module.exports = (require '../namespace').addNamespace('TransformOnlyStns', class TransformOnlyStns extends Neptune.PackageNamespace)
