# generated by Neptune Namespaces v0.5
# file: tests/caffeine/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Caffeine ||
Tests.addNamespace 'Caffeine', class Caffeine extends Neptune.Base
  ;