# generated by Neptune Namespaces v0.1.0
# file: tests/caffeine/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.Caffeine ||
Tests.addNamespace class Caffeine extends Neptune.Base
  ;