# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/NotWorking/namespace.coffee

Parser = require '../namespace'
module.exports = Parser.NotWorking ||
Parser.addNamespace 'NotWorking', class NotWorking extends Neptune.Base
  ;