// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/.Language/index.js

(module.exports = require('./namespace'))

.addModules({
  Arithmetic: require('./Arithmetic'),
  Empty:      require('./Empty')
});