# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/.Language/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Arithmetic: require './Arithmetic'
  Empty:      require './Empty'     