# generated by Neptune Namespaces v2.x.x
# file: tests/CaffeineScript/.Language/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.Language ||
CaffeineScript.addNamespace 'Language', class Language extends Neptune.Base
  ;
