# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/.Language/namespace.coffee

module.exports = (require '../namespace').addNamespace('Language', class Language extends Neptune.PackageNamespace)
