// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/.Language/namespace.js

module.exports = require('../namespace').addNamespace(
  'Language',
  class Language extends Neptune.PackageNamespace {}
);
