# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/index.coffee

module.exports = require './namespace'
.includeInNamespace require './CaffeineScript'
.addModules
  Lib:            require './Lib'           
  OperatorHelper: require './OperatorHelper'
  Parser:         require './parser'        
require './Rules'
require './Runtime'
require './SemanticTree'