# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/index.coffee

module.exports = require './namespace'
.includeInNamespace require './CaffeineScript'
.addModules
  Parser: require './parser'
require './Rules'