# generated by Neptune Namespaces v0.3.0
# file: caffeine_script/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.CaffeineScript ||
Neptune.addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.Base
  ;