# generated by Neptune Namespaces v0.6
# file: CaffeineScript/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.CaffeineScript ||
Neptune.addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.Base
  ;