# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/ComplexToJs/namespace.coffee

module.exports = (require '../namespace').addNamespace('ComplexToJs', class ComplexToJs extends Neptune.PackageNamespace)
