# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/ComplexToJs/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.ComplexToJs ||
SemanticTree.addNamespace 'ComplexToJs', class ComplexToJs extends Neptune.Base
  ;
