# generated by Neptune Namespaces
# file: tests/caffeine_script/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.CaffeineScript ||
Tests.addNamespace class CaffeineScript extends Neptune.Base
  ;