# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/StnsGeneratingJs/namespace.coffee

module.exports = (require '../namespace').addNamespace('StnsGeneratingJs', class StnsGeneratingJs extends Neptune.PackageNamespace)
