// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/StnsGeneratingJs/namespace.js

module.exports = require('../namespace').addNamespace(
  'StnsGeneratingJs',
  class StnsGeneratingJs extends Neptune.PackageNamespace {}
);
