# generated by Neptune Namespaces v2.x.x
# file: Perfs/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Perfs ||
Neptune.addNamespace 'Perfs', class Perfs extends Neptune.Base
  ;
