# generated by Neptune Namespaces v3.x.x
# file: Perfs/namespace.coffee

module.exports = (require 'neptune-namespaces').addNamespace 'Perfs', class Perfs extends Neptune.PackageNamespace
  @version: require('../../package.json').version
