# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/index.coffee

module.exports = require './namespace'
.addModules
  Helper: require './Helper'
require './Language'
require './Parser'