# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/index.coffee

module.exports = require './namespace'
.addModules
  CoffeeScript: require './CoffeeScript'
  Helper:       require './Helper'      
  Parser:       require './Parser'      
require './Language'