// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/index.js

(module.exports = require('./namespace'))

.addModules({
  BaseStn:        require('./BaseStn'),
  Compiler:       require('./Compiler'),
  Helper:         require('./Helper'),
  Lib:            require('./Lib'),
  OperatorHelper: require('./OperatorHelper'),
  ParseFailure:   require('./ParseFailure'),
  SourceMap:      require('./SourceMap')
});
require('./Parser');
require('./Preprocessors');
require('./Semantics');