# generated by Neptune Namespaces v2.x.x
# file: tests/CaffeineScript/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  BaseStn:        require './BaseStn'       
  Helper:         require './Helper'        
  Lib:            require './Lib'           
  OperatorHelper: require './OperatorHelper'
require './Parser'