# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.CaffeineScript ||
Tests.addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.Base
  ;