# generated by Neptune Namespaces v0.6
# file: tests/CaffeineScript/namespace.coffee

Tests = require '../namespace'
module.exports = Tests.CaffeineScript ||
Tests.addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.Base
  ;