# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/PlaceholderStns/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ComprehensionValueClauseStn: require './ComprehensionValueClauseStn'
  SemanticTokenStn:            require './SemanticTokenStn'           