// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/PlaceholderStns/namespace.js

module.exports = require('../namespace').addNamespace(
  'PlaceholderStns',
  class PlaceholderStns extends Neptune.PackageNamespace {}
);
