# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/PlaceholderStns/namespace.coffee

module.exports = (require '../namespace').addNamespace('PlaceholderStns', class PlaceholderStns extends Neptune.PackageNamespace)
