# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Language/index.coffee

module.exports = require './namespace'
.addModules
  Arithmetic: require './Arithmetic'
  Empty:      require './Empty'     