# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Language/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.Language ||
CaffeineScript.addNamespace 'Language', class Language extends Neptune.Base
  ;