# generated by Neptune Namespaces v0.1.0
# file: caffeine/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Caffeine ||
Neptune.addNamespace class Caffeine extends Neptune.Base
  ;