# generated by Neptune Namespaces v0.5
# file: caffeine/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.Caffeine ||
Neptune.addNamespace 'Caffeine', class Caffeine extends Neptune.Base
  ;