# generated by Neptune Namespaces v0.3.0
# file: caffeine/namespace.coffee

require 'neptune-namespaces'
module.exports = Neptune.Caffeine ||
Neptune.addNamespace 'Caffeine', class Caffeine extends Neptune.Base
  ;