# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/namespace.coffee

Neptune = require 'neptune-namespaces'
module.exports = Neptune.CaffeineScript ||
Neptune.addNamespace 'CaffeineScript', class CaffeineScript extends Neptune.Base
  ;