# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/Rules/index.coffee

module.exports = require './namespace'
.addModules
  Blocks:             require './Blocks'            
  ControlFlow:        require './ControlFlow'       
  Expressions:        require './Expressions'       
  Functions:          require './Functions'         
  Literals:           require './Literals'          
  NamedTerminals:     require './NamedTerminals'    
  Operators:          require './Operators'         
  Root:               require './Root'              
  Statements:         require './Statements'        
  StructuredLiterals: require './StructuredLiterals'