# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/Rules/index.coffee

module.exports = require './namespace'
.addModules
  Blocks:                  require './Blocks'                 
  Classes:                 require './Classes'                
  Comments:                require './Comments'               
  Comprehensions:          require './Comprehensions'         
  ControlStructures:       require './ControlStructures'      
  DestructuringAssignment: require './DestructuringAssignment'
  Expressions:             require './Expressions'            
  Functions:               require './Functions'              
  LiteralArrays:           require './LiteralArrays'          
  LiteralObjects:          require './LiteralObjects'         
  Literals:                require './Literals'               
  LiteralStrings:          require './LiteralStrings'         
  Operators:               require './Operators'              
  Root:                    require './Root'                   
  Statements:              require './Statements'             
  Tokens:                  require './Tokens'                 
  Values:                  require './Values'                 