# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/JustTransforms/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.JustTransforms ||
SemanticTree.addNamespace 'JustTransforms', class JustTransforms extends Neptune.Base
  ;
