# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/JustTransforms/namespace.coffee

module.exports = (require '../namespace').addNamespace('JustTransforms', class JustTransforms extends Neptune.PackageNamespace)
