# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/CafSourceMap/namespace.coffee

module.exports = (require '../namespace').addNamespace('CafSourceMap', class CafSourceMap extends Neptune.PackageNamespace)
