# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Semantics/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Comprehensions:          require './Comprehensions'         
  ComprehensionsEfficient: require './ComprehensionsEfficient'