// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Semantics/index.js

(module.exports = require('./namespace'))

.addModules({
  Comprehensions:          require('./Comprehensions'),
  ComprehensionsEfficient: require('./ComprehensionsEfficient')
});