// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Semantics/namespace.js

module.exports = require('../namespace').addNamespace(
  'Semantics',
  class Semantics extends Neptune.PackageNamespace {}
);
