# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Semantics/namespace.coffee

module.exports = (require '../namespace').addNamespace('Semantics', class Semantics extends Neptune.PackageNamespace)
