# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/Working/index.coffee

module.exports = require './namespace'
.addModules
  Accessors:        require './Accessors'       
  Assignment:       require './Assignment'      
  AutoScoping:      require './AutoScoping'     
  Classes:          require './Classes'         
  Comments:         require './Comments'        
  ControlOperators: require './ControlOperators'
  Functions:        require './Functions'       
  Modules:          require './Modules'         
  Operators:        require './Operators'       
  Statements:       require './Statements'      
  Values:           require './Values'          
require './Literals'