# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/Working/namespace.coffee

Parser = require '../namespace'
module.exports = Parser.Working ||
Parser.addNamespace 'Working', class Working extends Neptune.Base
  ;