# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/JustToJs/namespace.coffee

module.exports = (require '../namespace').addNamespace('JustToJs', class JustToJs extends Neptune.PackageNamespace)
