# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/JustToJs/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.JustToJs ||
SemanticTree.addNamespace 'JustToJs', class JustToJs extends Neptune.Base
  ;
