# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/Literals/index.coffee

module.exports = require './namespace'
.addModules
  Arrays:  require './Arrays' 
  Objects: require './Objects'
  Strings: require './Strings'