# generated by Neptune Namespaces v2.x.x
# file: tests/CaffeineScript/Parser/Literals/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  ArrayLiterals:   require './ArrayLiterals'  
  KeywordLiterals: require './KeywordLiterals'
  NumberLiterals:  require './NumberLiterals' 
  ObjectLiterals:  require './ObjectLiterals' 
  StringLiterals:  require './StringLiterals' 