// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Parser/Literals/index.js

(module.exports = require('./namespace'))

.addModules({
  ArrayLiterals:   require('./ArrayLiterals'),
  KeywordLiterals: require('./KeywordLiterals'),
  NumberLiterals:  require('./NumberLiterals'),
  ObjectLiterals:  require('./ObjectLiterals'),
  StringLiterals:  require('./StringLiterals')
});