# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Parser/Literals/namespace.coffee

module.exports = (require '../namespace').addNamespace('Literals', class Literals extends Neptune.PackageNamespace)
