# generated by Neptune Namespaces v2.x.x
# file: tests/CaffeineScript/Parser/Literals/namespace.coffee

Parser = require '../namespace'
module.exports = Parser.Literals ||
Parser.addNamespace 'Literals', class Literals extends Neptune.Base
  ;
