// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Parser/Literals/namespace.js

module.exports = require('../namespace').addNamespace(
  'Literals',
  class Literals extends Neptune.PackageNamespace {}
);
