# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/Working/Literals/namespace.coffee

Working = require '../namespace'
module.exports = Working.Literals ||
Working.addNamespace 'Literals', class Literals extends Neptune.Base
  ;