# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Preprocessors/index.coffee

module.exports = require './namespace'
module.exports
.addModules
  Comments:                require './Comments'               
  NormalizeIndentation:    require './NormalizeIndentation'   
  TestPreprocessorsHelper: require './TestPreprocessorsHelper'