// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Preprocessors/index.js

(module.exports = require('./namespace'))

.addModules({
  Comments:                require('./Comments'),
  NormalizeIndentation:    require('./NormalizeIndentation'),
  TestPreprocessorsHelper: require('./TestPreprocessorsHelper')
});