# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Preprocessors/namespace.coffee

module.exports = (require '../namespace').addNamespace('Preprocessors', class Preprocessors extends Neptune.PackageNamespace)
