// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Preprocessors/namespace.js

module.exports = require('../namespace').addNamespace(
  'Preprocessors',
  class Preprocessors extends Neptune.PackageNamespace {}
);
