# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/index.coffee

module.exports = require './namespace'
.addModules
  Assignment:   require './Assignment'  
  CoffeeScript: require './CoffeeScript'
require './NotWorking'
require './Working'