// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Parser/index.js

(module.exports = require('./namespace'))

.addModules({
  Accessors:               require('./Accessors'),
  Assignment:              require('./Assignment'),
  AutoScoping:             require('./AutoScoping'),
  Classes:                 require('./Classes'),
  CoffeeScript:            require('./CoffeeScript'),
  Comments:                require('./Comments'),
  Comprehensions:          require('./Comprehensions'),
  ComprehensionsEfficient: require('./ComprehensionsEfficient'),
  ControlStructures:       require('./ControlStructures'),
  Destructuring:           require('./Destructuring'),
  Extract:                 require('./Extract'),
  FunctionDefinition:      require('./FunctionDefinition'),
  FunctionInvocation:      require('./FunctionInvocation'),
  Import:                  require('./Import'),
  Modules:                 require('./Modules'),
  Operators:               require('./Operators'),
  RegExp:                  require('./RegExp'),
  Require:                 require('./Require'),
  ReservedVariables:       require('./ReservedVariables'),
  Scope:                   require('./Scope'),
  SpacesAndTabs:           require('./SpacesAndTabs'),
  Statements:              require('./Statements'),
  Structuring:             require('./Structuring'),
  Switch:                  require('./Switch'),
  Values:                  require('./Values')
});
require('./Literals');