# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/index.coffee

module.exports = require './namespace'
.addModules
  CoffeeScript:  require './CoffeeScript' 
  SpacesAndTabs: require './SpacesAndTabs'
require './ControlStructures'
require './Working'