# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/index.coffee

module.exports = require './namespace'
.addModules
  BasicLiterals:      require './BasicLiterals'     
  CoffeeScript:       require './CoffeeScript'      
  FunctionDefinition: require './FunctionDefinition'
  Misc:               require './Misc'              
  Operators:          require './Operators'         
  StructuredLiterals: require './StructuredLiterals'