# generated by Neptune Namespaces v3.x.x
# file: tests/CaffeineScript/Parser/namespace.coffee

module.exports = (require '../namespace').addNamespace('Parser', class Parser extends Neptune.PackageNamespace)
require './Literals/namespace'