# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.Parser ||
CaffeineScript.addNamespace 'Parser', class Parser extends Neptune.Base
  ;