// generated by Neptune Namespaces v4.x.x
// file: tests/CaffeineScript/Parser/namespace.js

module.exports = require('../namespace').addNamespace(
  'Parser',
  class Parser extends Neptune.PackageNamespace {}
);
require('./Literals/namespace');