// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/index.js

(module.exports = require('./namespace'))

.addModules({
  AccessorChainStn:       require('./AccessorChainStn'),
  BaseStn:                require('./BaseStn'),
  BasicStns:              require('./BasicStns'),
  ScopeStnMixin:          require('./ScopeStnMixin'),
  UniqueIdentifierHandle: require('./UniqueIdentifierHandle'),
  ValueBaseCaptureStn:    require('./ValueBaseCaptureStn')
});
require('./PlaceholderStns');
require('./StnsGeneratingJs');
require('./TransformOnlyStns');