# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/SemanticTree/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.SemanticTree ||
CaffeineScript.addNamespace 'SemanticTree', class SemanticTree extends Neptune.Base
  ;