// generated by Neptune Namespaces v4.x.x
// file: CaffeineScript/SemanticTree/namespace.js

module.exports = require('../namespace').addNamespace(
  'SemanticTree',
  class SemanticTree extends Neptune.PackageNamespace {}
);
require('./PlaceholderStns/namespace');
require('./StnsGeneratingJs/namespace');
require('./TransformOnlyStns/namespace');