# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/namespace.coffee

module.exports = (require '../namespace').addNamespace('SemanticTree', class SemanticTree extends Neptune.PackageNamespace)
require './ComplexToJs/namespace';
require './JustToJs/namespace';
require './JustToJsWithTransforms/namespace';
require './JustTransforms/namespace'