# generated by Neptune Namespaces v1.x.x
# file: tests/CaffeineScript/Parser/ControlStructures/namespace.coffee

Parser = require '../namespace'
module.exports = Parser.ControlStructures ||
Parser.addNamespace 'ControlStructures', class ControlStructures extends Neptune.Base
  ;