# generated by Neptune Namespaces v2.x.x
# file: CaffeineScript/SemanticTree/JustToJsWithTransforms/namespace.coffee

SemanticTree = require '../namespace'
module.exports = SemanticTree.JustToJsWithTransforms ||
SemanticTree.addNamespace 'JustToJsWithTransforms', class JustToJsWithTransforms extends Neptune.Base
  ;
