# generated by Neptune Namespaces v3.x.x
# file: CaffeineScript/SemanticTree/JustToJsWithTransforms/namespace.coffee

module.exports = (require '../namespace').addNamespace('JustToJsWithTransforms', class JustToJsWithTransforms extends Neptune.PackageNamespace)
