# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/Runtime/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Runtime'
.addModules
  ArrayCompactFlatten: require './ArrayCompactFlatten'
  Iteration:           require './Iteration'          
  Lib:                 require './Lib'                