# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/Runtime/index.coffee

module.exports = require './namespace'
.includeInNamespace require './Runtime'
.addModules
  Iteration: require './Iteration'
  Lib:       require './Lib'      