# generated by Neptune Namespaces v1.x.x
# file: CaffeineScript/Runtime/namespace.coffee

CaffeineScript = require '../namespace'
module.exports = CaffeineScript.Runtime ||
CaffeineScript.addNamespace 'Runtime', class Runtime extends Neptune.Base
  ;